/* eslint-disable react-native/sort-styles */
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  // Ejemplo de estilos para el carrusel (ajusta según tu línea gráfica)
  // Añade estos estilos a tu archivo styles/Explore.js
  clusteringIndicator: {
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderColor: '#4285F4',
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
    position: 'absolute',
    right: 10,
    top: 10,
  },
  searchButton: {
    marginLeft: 5,
    padding: 10,
  },
  clusteringText: {
    color: '#4285F4',
    fontWeight: 'bold',
  },
  markerCount: {
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 5,
    elevation: 2,
    padding: 5,
    position: 'absolute',
    right: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    top: 100,
  },
  markerCountText: {
    color: '#333',
    fontSize: 12,
    fontWeight: '500',
  },
  // eslint-disable-next-line react-native/sort-styles
  applyButton: {
    alignItems: 'center',
    backgroundColor: '#4285F4',
    borderRadius: 10,
    flex: 1,
    marginLeft: 10,
    paddingVertical: 15,
  },
  applyButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  carouselContainer: {
    alignItems: 'center',
    paddingVertical: 10,
  },
  carouselItem: {
    alignItems: 'center',
    backgroundColor: '#f0f0f0',
    borderRadius: 10,
    height: 70,
    justifyContent: 'center',
    marginHorizontal: 10,
    width: 120,
  },
  carouselItemActive: {
    backgroundColor: '#4285F4',
  },
  carouselText: {
    color: '#666',
    fontWeight: '500',
    marginTop: 5,
  },

  carouselTextActive: {
    color: '#fff',
  },

  clearButton: {
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderColor: '#ddd',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    marginRight: 10,
    paddingVertical: 15,
  },
  clearButtonText: {
    color: '#666',
    fontSize: 16,
    fontWeight: '600',
  },
  clearFilterChip: {
    alignItems: 'center',
    backgroundColor: '#f44336',
    borderRadius: 20,
    elevation: 2,
    flexDirection: 'row',
    marginRight: 10,
    paddingHorizontal: 16,
    paddingVertical: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  clearFilterText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 6,
  },
  clearSearchButton: {
    padding: 4,
  },
  container: {
    flex: 1,
  },
  dateOption: {
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
    paddingHorizontal: 15,
    paddingVertical: 12,
  },
  dateOptionSeparator: {
    backgroundColor: '#f5f5f5',
    color: '#666',
    fontSize: 14,
    fontWeight: 'bold',
    marginVertical: 5,
    paddingHorizontal: 15,
    paddingVertical: 8,
  },
  dateOptionText: {
    color: '#333',
    fontSize: 16,
  },
  dateOptionsList: {
    maxHeight: 400,
  },
  datePickerButton: {
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderColor: '#ddd',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  datePickerButtonText: {
    color: '#666',
    fontSize: 14,
    marginLeft: 8,
  },
  datePickerContainer: {
    backgroundColor: 'white',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    bottom: 0,
    padding: 20,
    position: 'absolute',
    width: '100%',
  },
  datePickerHeader: {
    alignItems: 'center',
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
    paddingBottom: 15,
  },
  datePickerModal: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  datePickerTitle: {
    color: '#333',
    fontSize: 18,
    fontWeight: 'bold',
  },
  dateRangeChip: {
    alignItems: 'center',
    backgroundColor: '#e8f0fe',
    borderColor: '#4285F4',
    borderRadius: 20,
    borderWidth: 1,
    elevation: 2,
    flexDirection: 'row',
    marginRight: 10,
    paddingHorizontal: 16,
    paddingVertical: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  dateRangeContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 20,
  },
  dateRangeSeparator: {
    color: '#666',
    fontSize: 18,
    fontWeight: 'bold',
    marginHorizontal: 10,
  },
  dropdownOverlay: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  eventCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    elevation: 3,
    marginRight: 15,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    width: 220,
  },
  eventCardContent: {
    padding: 12,
  },
  eventCardDescription: {
    color: '#666',
    fontSize: 14,
    marginBottom: 8,
  },
  eventCardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  eventCardTime: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  eventCardTimeText: {
    color: '#666',
    fontSize: 12,
    marginLeft: 4,
  },
  eventCardTitle: {
    color: '#333',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  eventDescription: {
    color: '#666',
    fontSize: 14,
    marginTop: 5,
  },
  eventImage: {
    width: '100%', // Cambia el ancho a 100%
    height: 100, // Mantiene la altura original
    borderRadius: 8, // Conserva el radio de los bordes
  },
  eventModalCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    elevation: 3,
    marginBottom: 10,
    marginRight: 15,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    width: 220,
  },
  eventTitle: {
    color: '#333',
    fontSize: 16,
    fontWeight: 'bold',
  },
  eventsButton: {
    alignSelf: 'center',
    backgroundColor: '#4285F4',
    borderRadius: 25,
    bottom: 10,
    elevation: 4,
    paddingHorizontal: 60,
    paddingVertical: 8,
    position: 'absolute',
    zIndex: 10,
  },
  eventsButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  eventsModalContainer: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  eventsModalContent: {
    alignItems: 'center',
    backgroundColor: 'white',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    justifyContent: 'flex-end',
    maxHeight: '85%',
    padding: 20,
  },
  eventsModalHeader: {
    alignItems: 'center',
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    paddingBottom: 10,
  },
  eventsModalTitle: {
    color: '#333',
    fontSize: 18,
    fontWeight: 'bold',
  },
  filterActionsContainer: {
    flexDirection: 'row',
    marginBottom: 20,
    marginTop: 30,
  },
  filterButton: {
    padding: 8,
  },
  filterButtonActive: {
    backgroundColor: '#4285F4',
  },
  filterChip: {
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 20,
    elevation: 2,
    flexDirection: 'row',
    marginRight: 10,
    paddingHorizontal: 16,
    paddingVertical: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  filterGridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  filterGridItem: {
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    marginBottom: 12,
    padding: 16,
    width: '23%',
  },
  filterGridText: {
    color: '#666',
    fontSize: 12,
    marginTop: 8,
    textAlign: 'center',
  },
  filterText: {
    color: '#666',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 6,
  },
  filterTextActive: {
    color: '#fff',
  },
  filtersScrollContainer: {
    paddingVertical: 5,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  modalContainer: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: 'white',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '85%',
    padding: 25,
  },
  modalHeader: {
    alignItems: 'center',
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingBottom: 15,
  },
  modalTitle: {
    color: '#333',
    fontSize: 18,
    fontWeight: 'bold',
  },
  myLocationButton: {
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 28,
    elevation: 4,
    height: 56,
    justifyContent: 'center',
    position: 'absolute',
    right: 22,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    top: 160,
    width: 56,
    zIndex: 1,
  },
  nearbyEventsContainer: {
    bottom: 80,
    left: 0,
    paddingHorizontal: 20,
    position: 'absolute',
    right: 0,
    zIndex: 10,
  },
  nearbyEventsScrollContainer: {
    paddingBottom: 10,
  },
  noResultsContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 30,
  },
  noResultsText: {
    color: '#666',
    fontSize: 16,
  },
  populationDropdownButton: {
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderColor: '#ddd',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
    padding: 12,
  },
  populationDropdownButtonText: {
    color: '#333',
    fontSize: 16,
  },
  populationDropdownContainer: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    height: '70%',
    maxHeight: '80%',
  },
  populationDropdownHeader: {
    alignItems: 'center',
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
    paddingBottom: 15,
  },
  populationDropdownTitle: {
    color: '#333',
    fontSize: 18,
    fontWeight: 'bold',
  },
  populationList: {
    flex: 1, // Ocupará el espacio restante después del encabezado y la barra de búsqueda
    marginTop: 10,
  },
  populationListItem: {
    alignItems: 'center',
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  populationListItemSelected: {
    backgroundColor: '#4285F4',
  },
  populationListItemText: {
    color: '#333',
    fontSize: 16,
  },
  populationListItemTextSelected: {
    color: '#fff',
    fontWeight: '500',
  },
  removeFilterIcon: {
    marginLeft: 5,
  },
  searchBar: {
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 28,
    flexDirection: 'row',
    marginTop: -10,
    paddingHorizontal: 10,
    paddingVertical: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    width: '100%',
  },
  searchContainer: {
    alignItems: 'center',
    paddingHorizontal: 20,
    position: 'absolute',
    top: 80,
    width: '100%',
    zIndex: 1,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    height: 40,
  },
  searchPopulationContainer: {
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    flexDirection: 'row',
    marginBottom: 15,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  searchPopulationIcon: {
    marginRight: 8,
  },
  searchPopulationInput: {
    color: '#333',
    flex: 1,
    fontSize: 16,
  },
  sectionTitle: {
    color: '#333',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 15,
    marginTop: 5,
  },
  simpleDatePickerContainer: {
    marginVertical: 10,
  },
});
