name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Disable shallow clone for full analysis

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.1'

      - name: Install dependencies
        run: yarn install

      - name: Remove Pods directory
        run: rm -rf ios/Pods
        shell: bash

      - name: Install Build Tools
        run: sudo apt-get install -y cmake

      - name: Generate compile_commands.json
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          cd ..

      - name: Debug SonarQube Config
        run: cat sonar-project.properties

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.exclusions=ios/Pods/**
            -Dsonar.cfamily.compile-commands=build/compile_commands.json

      - name: Clear SonarQube Cache
        run: rm -rf ~/.sonar/cache
        shell: bash