name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Deshabilitar clon superficial para análisis completo

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Eliminar directorio Pods para evitar problemas en el análisis
      - name: Remove Pods directory
        run: rm -rf ios/Pods
        shell: bash

      # Ver sonar-project.properties
      - name: Debug SonarQube Config
        run: cat sonar-project.properties

      # Ejecutar análisis SonarQube
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.exclusions=ios/Pods/**

      # Limpiar caché de SonarQube (opcional)
      - name: Clear SonarQube Cache
        run: rm -rf ~/.sonar/cache
        shell: bash
